2024-05-08 17:28:23,374 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-08 17:28:23,374 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Configure stats pid to 14340
2024-05-08 17:28:23,374 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sbene\.config\wandb\settings
2024-05-08 17:28:23,374 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Loading settings from d:\Dev\Projects D\Anja\MA\wandb\settings
2024-05-08 17:28:23,374 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-08 17:28:23,374 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_init.py:_log_setup():520] Logging user logs to d:\Dev\Projects D\Anja\MA\wandb\run-20240508_172823-d5xkxnwl\logs\debug.log
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_init.py:_log_setup():521] Logging internal logs to d:\Dev\Projects D\Anja\MA\wandb\run-20240508_172823-d5xkxnwl\logs\debug-internal.log
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_init.py:init():560] calling init triggers
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'model': 'CLIP', 'batch_size': 8, 'n_epochs': 10, 'lr': 0.0001}
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_init.py:init():610] starting backend
2024-05-08 17:28:23,382 INFO    MainThread:14340 [wandb_init.py:init():614] setting up manager
2024-05-08 17:28:23,390 INFO    MainThread:14340 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-08 17:28:23,390 INFO    MainThread:14340 [wandb_init.py:init():622] backend started and connected
2024-05-08 17:28:23,406 INFO    MainThread:14340 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-08 17:28:23,406 INFO    MainThread:14340 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-08 17:28:23,406 INFO    MainThread:14340 [wandb_init.py:init():711] updated telemetry
2024-05-08 17:28:23,437 INFO    MainThread:14340 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-08 17:28:23,799 WARNING MsgRouterThr:14340 [router.py:message_loop():77] message_loop has been closed
2024-05-08 17:28:23,815 ERROR   MainThread:14340 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-08 17:28:23,815 ERROR   MainThread:14340 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "d:\Dev\miniconda\envs\anja-ma\lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
  File "d:\Dev\miniconda\envs\anja-ma\lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
